server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mavooripachadi}
    username: ${DB_USER:root}
    password: ${DB_PASS:Mad@1234}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 50
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: 'classpath:db/migration'

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

payments:
  razorpay:
    key: ${RAZORPAY_KEY_ID:rzp_test_RUbsNadTP2WNOd}
    secret: ${RAZORPAY_KEY_SECRET:56XTLHV6EQ7FdTJQPKWu6PvK}
    base-url: ${RAZORPAY_BASE_URL:https://api.razorpay.com/v1}

app:
  security:
    allowed-origins:
      - http://localhost:4200
      - http://localhost:8085
      - https://maavooripachadi.com
      - https://www.maavooripachadi.com
  orders:
    notifications:
      email-enabled: true
      whatsapp-enabled: true
      from-email: orders@maavooripachadi.com
      ops-display-name: Kitchen Ops Desk
      support-whatsapp-link: https://wa.me/918555859667
      owner-emails:
       # - kitchen@maavooripachadi.com
        - surapureddymadhu57@gmail.com
      owner-whatsapp-numbers:
        - 918555859967
  whatsapp:
    enabled: false
    phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID:}
    access-token: ${WHATSAPP_ACCESS_TOKEN:}
    api-base: https://graph.facebook.com/v18.0
    default-country-code: 91
